service: self-help-service-portal-backend


provider: 
  name: aws
  runtime: nodejs20.x
  region: ap-south-1
  profile: ${self:custom.profile.${opt:stage, 'swanandp'}}
  environment:
    USER_POOL_ID: ${self:custom.userpools.poolid.${opt:stage, 'swanandp'}}
    CLIENT_ID: ${self:custom.userpools.clientid.${opt:stage, 'swanandp'}}
    BUCKET_NAME: ${self:custom.buckets.${opt:stage, 'swanandp'}}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:PutItem
        - dynamodb:GetItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:Scan
        - dynamodb:Query
      Resource: "*"

    - Effect: Allow
      Action:
        - s3:PutObject
        - s3:GetObject
        - s3:DeleteObject
        - s3:ListBucket  
      Resource: "arn:aws:s3:::self-help-service-portal/*"
      
    - Effect: Allow
      Action:
        - cognito-idp:AdminCreateUser
        - cognito-idp:AdminDeleteUser
        - cognito-idp:AdminUpdateUserAttributes
        - cognito-idp:AdminGetUser
        - cognito-idp:AdminInitiateAuth
        - cognito-idp:AdminSetUserPassword
      Resource: "arn:aws:cognito-idp:ap-south-1:087484585762:userpool/ap-south-1_VS3TzsPNb"
custom:
  profile: 
    swanandp: swanand-dev
  userpools:
    poolid:
      swanandp: ap-south-1_VS3TzsPNb
    clientid:
      swanandp: 3btfg0h20rtnfbhla85gv66lht
  buckets:
    swanandp: self-help-service-portal
  
functions:
  app:
    handler: dist/app.handler
    events:
      - http:
          path: /users/admin/register
          method: post
          cors: true
      - http:
          path: /users/admin/login
          method: post
          cors: true
      - http:
          path: /users/admin/employees
          method: post
          cors: true
      - http:
          path: /users/employee/login
          method: post
          cors: true
      - http:
          path: /users/teams
          method: post
          cors: true
      - http:
          path: /users/teams
          method: get
          cors: true
      - http:
          path: /users/{userId}
          method: get
          cors: true
      - http:
          path: /users
          method: get
          cors: true
      - http:
          path: /users/teams/{teamId}
          method: get
          cors: true
      - http:
          path: /users/teams/{teamId}
          method: put
          cors: true
      - http:
          path: /users/teams/{teamId}
          method: delete
          cors: true
      - http:
          path: /updates
          method: post
          cors: true
      - http:
          path: /updates/team/{teamId}
          method: get
          cors: true
      - http:
          path: /updates/update/{updateId}
          method: get
          cors: true
      - http:
          path: /updates/update/{updateId}
          method: put
          cors: true
      - http:
          path: /updates/update/{updateId}
          method: delete
          cors: true
      - http:
          path: /attendance
          method: post
          cors: true
      - http:
          path: /attendance/{employeeId}
          method: get
          cors: true
      - http:
          path: /requests
          method: post
          cors: true
      - http:
          path: /requests
          method: get
          cors: true
      - http:
          path: /requests/{requestId}
          method: get
          cors: true
      - http:
          path: /requests/{requestId}
          method: put
          cors: true
      - http:
          path: /requests/employee/{employeeId}
          method: get
          cors: true
      - http:
          path: /finance/pay
          method: post
          cors: true
      - http:
          path: /finance/{employeeId}
          method: get
          cors: true
      - http:
          path: /finance/team/{teamName}
          method: get
          cors: true
      - http:
          path: /tasks
          method: post
          cors: true
      - http:
          path: /tasks
          method: get
          cors: true
      - http:
          path: /tasks/{taskId}
          method: get
          cors: true
      - http:
          path: /tasks/{taskId}
          method: put
          cors: true
      - http:
          path: /tasks/{taskId}
          method: delete
          cors: true
      - http:
          path: /tasks/{taskId}/status
          method: put
          cors: true
      - http:
          path: /tasks/{taskId}/comments
          method: post
          cors: true
      - http:
          path: /task-requests
          method: post
          cors: true
      - http:
          path: /task-requests/inbox
          method: get
          cors: true
      - http:
          path: /task-requests/sent
          method: get
          cors: true
      - http:
          path: /task-requests/{taskRequestId}/negotiate
          method: patch
          cors: true
      - http:
          path: /task-requests/{taskRequestId}/approve
          method: patch
          cors: true
      - http:
          path: /task-requests/{taskRequestId}/reject
          method: patch
          cors: true
      - http:
          path: /task-requests/{taskRequestId}/escalate
          method: patch
          cors: true
